### ISSUE TITLE
Bugs in the service

### ISSUE THREAD

**Issue by olyaave** [posadskiy/currency-converter#2] opened 2020-07-28 05:59 UTC
Good afternoon.

I wanted to use your library, but I found some problems:
1) The guide omits "new" before ConfigBuilder().

![image](https://user-images.githubusercontent.com/42898899/88623273-09807a80-d0be-11ea-8481-cb9a989b04ba.png)

2) In the CurrencyConvertService class, the argument config.getOpenExchangeRatesApiKey() is mixed up in line 25.

![image](https://user-images.githubusercontent.com/42898899/88623410-59f7d800-d0be-11ea-8089-11e900f56416.png)

3) I wanted to use the first to work. When requesting the first service, this error appears. I have Internet access, but I couldn't figure out what the problem was.

![image](https://user-images.githubusercontent.com/42898899/88623729-076aeb80-d0bf-11ea-80cb-528c64ac7814.png)

Thank you in advance for your answer.

**Comment by posadskiy** [comment] 2020-07-28 17:04
@olyaave 
Hi!
Thanks for your comment. Points 1 and 2 are bugs, so it was fixed in the new version - 1.1.2. Please, update your dependency.
Error message from point 3 looks like an attempt to use service with no API key. 
Share with me code when you create CurrencyConverter instance, please. If it has your private API key, replace the key to any random string.

**Comment by olyaave** [comment] 2020-07-28 21:00
Hi!
I can't update the dependency  because I can't find version 1.1.2.  :(

![image](https://user-images.githubusercontent.com/42898899/88720080-bbab5700-d13d-11ea-81d0-b197ebe2656d.png)

Here I create a Current Converter instance:

![image](https://user-images.githubusercontent.com/42898899/88720716-bf8ba900-d13e-11ea-96f4-46ee05e751fe.png)

**Comment by posadskiy** [comment] 2020-07-30 07:37
Hi, @olyaave !
It's the correct way to create a class instance. Possibly, your API key is invalid or is not suitable for free use (only free keys for CurrencyConverterApi.com are supported now).
You can check key is working or not via GET request to _https://free.currconv.com/api/v7/convert?q=USD_EUR&compact=ultra&apiKey=KEY_, where KEY is your API key. If the key is correct, you should see anything like that: {"USD_EUR":0.850735}, error message otherwise. If the key is incorrect, get a new one in the user page of currencyconverterapi.com.

If the problem isn't going away, I suggest you update your dependency to version 1.1.3 (the version is available in sonatype nexus repository right now and will be loaded to mvnrepository today later, I hope), try to run your application and attach here error stacktrace. New version better works with network exceptions.

Anyway, you can use any of the other two services.

**Comment by olyaave** [comment] 2020-07-30 17:15
Hi!
I tried to find the error for a long time, but it was unsuccessful. For some reason, the request is executed normally in the Java console project, but an error appears in the Android project. I use the first and second services, because the third one doesn't have a free version. I noticed that the error starts at the place where HttpUrlConnection.Builder tries to convert null to a string. Could there be a problem if I run the query non-asynchronously? 
Here is a stack of errors.

D/NetworkSecurityConfig: No Network Security Config specified, using platform default
W/CurrencyConvertService: Service CurrencyConverterApi.Com has problem currently. Please, try again later. If problem still happens, create ticket on github.com/posadskiy/currency-converter or send e-mail to admin@posadskiy.com
W/System.err: android.os.NetworkOnMainThreadException
W/System.err:     at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1513)
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:117)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
        at java.net.InetAddress.getAllByName(InetAddress.java:1154)
W/System.err:     at com.android.okhttp.Dns$1.lookup(Dns.java:39)
        at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:175)
        at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:141)
        at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:83)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
        at com.posadskiy.currencyconverter.util.NetworkUtils.getBufferReaderByUrl(NetworkUtils.java:22)
        at com.posadskiy.currencyconverter.source.CurrencyConverterApiSource.rate(CurrencyConverterApiSource.java:18)
        at com.posadskiy.currencyconverter.service.CurrencyConvertService.rate(CurrencyConvertService.java:19)
        at com.posadskiy.currencyconverter.CurrencyConverter.rate(CurrencyConverter.java:327)
        at com.example.urrencyonverter.ApiService.ToConvert(ApiService.java:46)
        at com.example.urrencyonverter.MainActivity.onCreate(MainActivity.java:21)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
W/CurrencyConvertService: Service CurrencyLayer.Com has problem currently. Please, try again later. If problem still happens, create ticket on github.com/posadskiy/currency-converter or send e-mail to admin@posadskiy.com
W/System.err: android.os.NetworkOnMainThreadException
W/System.err:     at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1513)
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:117)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
        at java.net.InetAddress.getAllByName(InetAddress.java:1154)
        at com.android.okhttp.Dns$1.lookup(Dns.java:39)
W/System.err:     at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:175)
        at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:141)
        at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:83)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
        at com.posadskiy.currencyconverter.util.NetworkUtils.getBufferReaderByUrl(NetworkUtils.java:22)
        at com.posadskiy.currencyconverter.source.CurrencyLayerSource.rate(CurrencyLayerSource.java:18)
W/System.err:     at com.posadskiy.currencyconverter.service.CurrencyConvertService.rate(CurrencyConvertService.java:31)
        at com.posadskiy.currencyconverter.CurrencyConverter.rate(CurrencyConverter.java:327)
        at com.example.urrencyonverter.ApiService.ToConvert(ApiService.java:46)
        at com.example.urrencyonverter.MainActivity.onCreate(MainActivity.java:21)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
W/System.err: com.posadskiy.currencyconverter.exception.CurrencyConverterException: Nothing working services. Please, try later again. If problem stay, create a ticket on github.com/posadskiy/currency-converter
        at com.posadskiy.currencyconverter.service.CurrencyConvertService.rate(CurrencyConvertService.java:52)
        at com.posadskiy.currencyconverter.CurrencyConverter.rate(CurrencyConverter.java:327)
        at com.example.urrencyonverter.ApiService.ToConvert(ApiService.java:46)
        at com.example.urrencyonverter.MainActivity.onCreate(MainActivity.java:21)
W/System.err:     at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Closed as completed** 2020-08-01 08:00 UTC
Labels: bug, documentation

**Comment by posadskiy** [comment] 2020-08-01 13:17
@olyaave 
Hi!
Added [example](https://github.com/posadskiy/currency-converter/blob/master/examples/android/CurrencyConverterAsyncTask.java) of how to work with a network-required library from Android.
As I understood, you already tried this way and got expected results.

**Comment by olyaave** [comment] 2020-08-03 18:13
Hi
Yes, thank you for your time.
